### ISSUE TITLE
Collection should be able to save/update/delete multiple objects

### ISSUE THREAD

**Issue by OneMoreThing** [deployd/deployd#100]
Deployd should accept in collection's API also array of objects, so for example the POST should be able to save multiple objects in the collection, such as

POST / todos
[{"title": "Walk the dog", "category": "red"}, {"title": "Take the cat", "category": "green"}]

or through a native handler (without implement a custom resource), something like  

POST /todos/array

**Comment by pmb6tz** [comment]
Anything ever happen with this? It'd be really nice to be able to update multiple objects in one POST/PUT.. I don't see it in the 0.7 changelog though.

**Comment by andreialecu** [comment]
@pmb6tz it's possible to dispatch raw mongo queries since https://github.com/deployd/deployd/pull/608 

You will need to write the code to do that yourself though, preferably in a [dpd-event](https://github.com/deployd/dpd-event)

See http://mongodb.github.io/node-mongodb-native/2.1/tutorials/crud/ for `updateMany` or `findAndModify`.
