### ISSUE TITLE
Dpd promises is broken?

### ISSUE THREAD

**Issue by PaulMaly** [deployd/deployd#462]
Hello everyone! I don't understand how to use promises in dpd.js lib to access the result. Is it broken? Could anyone provide me working example how to use it?

One more proposal, maybe it will be better to use Node-style (error argument first) for callbacks? For me, it's more convenient.

And additional question, whether any date when 0.8 version will be released?

**Comment by NicolasRitouet** [comment]
Hi @PaulMaly 
I haven't tried the promises yet, I'll have to write some docs soon about this, so I can update you on this.

However, I can give you some information regarding a version 0.8.
We're close to the release.
We still have a [few issues open](https://github.com/deployd/deployd/milestones/0.8.0) but there're small.
I hope we'll be ready to release mid-january.
We still depend on the core developers because we don't have access to npm to publish the new release.
In the meanwhile, we'll tag a new pre-release on github so that you can test the version.

**Comment by PaulMaly** [comment]
Thanks for the answer, Nicolas! I'm really glad to hear it. Seems, I've already resolved my misunderstanding regarding dpd promises. 

Regarding new version, should we expect some new features or it will be more about bug-fixing?

**Comment by PaulMaly** [comment]
I think this issue can be closed. https://github.com/deployd/deployd/issues/482
