### ISSUE TITLE
hide("property")

### ISSUE THREAD

**Issue by alirafiq** [deployd/deployd#505]
I am going to hide some field like logs . logs is an array of object which maintain visit of site with object of ip address and dated , now the count of this array is more then 50k and size is arround 3 to 4mb , 
when i am going to hide this parameter on post/put/get at this collection events, it is not going to load the logs parameter in results . but when monitor the mongodb , it fetch all data and having more the 4 mb response per query. 
I think issue is deployd hide the parameter from lib but fetch all document from collection.

**Comment by andreialecu** [comment]
Just wondering, why are you storing this big field in a row? Couldn't you store it in a separate collection instead?

**Comment by alirafiq** [comment]
OK , i did save it into another collection , when it will update or insert,  it will respond me the whole document on callback. I will be stand at the same position

**Comment by andreialecu** [comment]
Well, what I meant was, if you have an array, store the items in the array as records of a new collection. Don't put all of them in one field. I don't think it's a good practice having fields several megabytes in size. The max mongo will let you store in a document is 16 megabytes anyway, and that's a stretch.

**Comment by alirafiq** [comment]
well thats size is about 3 to 4 mb in a 6 months. after a year it will save into new document/row. 
Well push one  small object into array may be good practices in schema less databse. 
and there is another issue that cant get more then 750 record from collections

**Comment by andreialecu** [comment]
This is by design in deployd. 

Before you can do a `hide()`, deployd gives you access to the value of the property in the script by `this.fieldName`. For it to be populated, it needs to get it. `hide()` is just for hiding from the result, it doesn't influence what mongo returns. You can however pass a `$fields` query to exclude the field before querying: http://docs.deployd.com/docs/collections/reference/querying-collections.html

I'm not sure what your exact use case is, but if it is actually a log and you're modifying a field on a document to add new log lines often, this is not a good practice in any sort of database be it schema-less or not.

**Comment by alirafiq** [comment]
Thanks but , i have an ads server and reporting the view of website from these IP's and if i create it new document/row , deployd does not return more then 750 records.

**Comment by andreialecu** [comment]
You could use `$limit` and `$skip` to get records in batches.
