### ISSUE TITLE
No error if an internal collection call is canceled

### ISSUE THREAD

**Issue by Maddis1337** [deployd/deployd#511]
dpd.mycollection.get(...)
    .catch(function(err){
        // will not be called
    }) 
will not catch anythig if I use cancel() within the get event of mycollection, I will never know if my get had an error.

**Comment by Maddis1337** [comment]
I will close this for now because I have to verify that it is not an error in a forked version I am using.

**Comment by Maddis1337** [comment]
Ok, I should read more: http://docs.deployd.com/docs/collections/reference/event-api.html#s-cancel()-764

>  Note: In a GET event where multiple values are queried (such as on /posts), the cancel() function will remove the current item from the results without an error message.

**Comment by 0ff** [comment]
Actually, I think you might be up to something here.
This line here https://github.com/deployd/deployd/blob/master/lib/internal-client.js#L136 will result in recursion-errors not being treated as **errors** (by https://github.com/deployd/deployd/blob/master/lib/resources/collection/index.js#L327), but instead being handled like cancel, i.e. running into this error will just skip the affected records instead of telling you, that you ran into it.

This might be fixed by changing the first line into this:
```js
callback(null, new Error("Recursive call to " + urlKey + " detected"));
```
In my opinion this should actually be done, as I think just excluding the record is not the way to go about this particular error.
BTW: This does not break any tests, so a simple 1 line PR would be all that's needed. (Well - a test might be nice ;-))

Any opinions?
