### ISSUE TITLE
executed 'dpd create hello' but reported error

### ISSUE THREAD

**Issue by kaisatec** [deployd/deployd#517]
I installed deployed on osx, it worked.

but when I executed  'dpd create hello' , it reported error:

js-bson: Failed to load c++ bson extension, using pure JS version

Your comment welcome

ZW

**Comment by ericfong** [comment]
Cannot re-produce

what is your version for dpd (global install), node and mongodb ?

May try to clean npm cache clean and rm -rf ~/.node-gyp  and re-install deployd?

**Comment by ipepe** [comment]
I have this message also, I am on Mac OS and I am deploying my apps to OpenShift.rhcloud.com and when looking at logs at server, i can see that message also. But it's not an error, it's a warning. Normal nodejs processing should work, but maybe slower?

**Comment by NicolasRitouet** [comment]
If you have locally installed make, gcc and build-essential, you could build the c++ version of js-bon.
Since you don't have these dependencies, it will use the js version, which is a bit slower.

http://stackoverflow.com/questions/21656420/failed-to-load-c-bson-extension

Not a big issue and not related to Deployd.
