### ISSUE TITLE
Deployd vs Loopback etc

### ISSUE THREAD

**Issue by swift1** [deployd/deployd#614]
Hi,
I know I'm supposed to use the Google group for questions, but I don't wanna create a google account just for this, so I'll ask it here:
I heard the creators of Deployd all moved to Strongloop. Deployd seems like an awesome way to build backends for web apps, and I'm happy to see that the project is still being maintained by other fans here on github. But what's the current status of Deployd? Is there any good reason why the creators abandoned it (apart from money), and is it still a valid choice to go for Deployd instead of other noBackend/BaaS solutions? Is there any security concerns or other big reasons why this awesome framework hasn't skyrocketed in popularity? :)
(I know since I ask this question here, the answers might be biased, but I'm really interested to learn a bit more about this.)

**Comment by andreialecu** [comment]
My personal opinion:

Loopback is way more complex than Deployd, and may also have a lot of features you will not use. 

If you start a new project on Deployd, and are a good developer, odds are that you can understand the entire framework within a few weeks and when you come across something not working the way you want, you can easily patch it up by yourself and go on with your project. I personally like being able to have full control over the code I work with.

Deployd lets you do simple things really easy, but when you want to do more complex things you have to get creative.

Also, Deployd was dormant for the best part of 2 years, so that also has something to do with it.

**Comment by NicolasRitouet** [comment]
I'm closing this ticket, we already had many discussion about this, check the closed tickets or go on gitter to talk to the deployd users.
