### ISSUE TITLE
need to know location of stored collecton in mogod

### ISSUE THREAD

**Issue by VikasKSahu** [deployd/deployd#721]
Hi i have created collection using delpyD, i am using eternal mongod server, when i am trying to get collection in mongodb i am not able to see, but all the stored collection displayed on browser when i run get method of deployd api. Any clue how i can get collection from the java code stored in mongod

**Comment by rgolea** [comment]
I think you might not be connecting to the external mongod instance. Try deleting from your project root folder the `data` folder. I'm pretty sure you will not get the data afterwards. That is because you might be running on the local instance.

Try doing this:

1. Make sure you have deployd installed as *local dependency* in your app.
2. Use [this gist](https://github.com/rgolea/angular-deployd-admin/blob/master/app.js) and execute your node app server from this file.

I will close this issue since it's quite frequent. Please feel free to reopen it if necessary.
