### ISSUE TITLE
How to custom Response json format？

### ISSUE THREAD

**Issue by jinwyp** [deployd/deployd#778]
The default format for query a orders  collection   is 

`
[
{id : 1, name : 'jacky'},
{id :2, name : 'andy'}
]`

I want to change output json like below 
`
{
success : true,
data : [{id : 1, name : 'jacky'},{id :2, name : 'andy'}]
}
`

How to do this in the ON GET EVENT?

**Comment by rgolea** [comment]
Hey @jinwyp let's take this in order:
First of all, you are already getting success/error on the status code of your request. You should only be checking that.
And secondly, you cannot do this in a collection on the GET event since you are not handling the response there and the get event is being run over each item that is being returned from the database. You might want to try using dpd-event if your response has to be necessarily in that format but you are creating a collection resource and an event resource on each database collection.

Hope this helps. Cheers!
