### ISSUE TITLE
client emit

### ISSUE THREAD

**Issue by thbl** [deployd/deployd#795]
Hello

Is it possible to use the emit() on the client site somehow ?
etc. to make a more direct client <-> client chat app vs the one in  examples with post.

**Comment by andreialecu** [comment]
You'd have to hit the server via HTTP. But you can create a [dpd-event](https://github.com/deployd/dpd-event) which serves as an endpoint that then redistributes the message, by issuing the `emit()` call from the server back to other clients.

I'm not sure why you'd want that though, since it's probably better to save chat messages in the database so they're available in case connections are dropped, and reconnected.
