### ISSUE TITLE
deploydDB reseting after a while on production

### ISSUE THREAD

**Issue by manoma2304** [deployd/deployd#852]
## Context
i uploaded my deployd app to heroku, i'm using the free plan, idk if that is why, but after some time inactive the deployd app will reset and will lose the listing of the mongodb it's connected to. For example if i create a collection called products and add data to it, after some time the app will reset and it will vanish from it. To solve that i have to create the collection again with the same name and props and the previous data will be there.

## Expected Behavior
even if it's reseting. Deployd should check the mongodb for data

## Actual Behavior
Deployd resets and don't check mongodb for data, resulting in a empty db

## Steps to Reproduce
1. add app to heroku with the free plan
2. create data using the production dashboard hosted on heroku
3. stay offline for some time until heroku sleeps your app
4. go back to your app
 
## Context
i'm setting up the db while working on a separated app that will use it for a backend + frontend architecture instead of a fullstack

## Your Environment
```
    "engines": {
        "node": "6.11.4",
        "npm": "3.10.10"
    },
    "dependencies": {
        "deployd": "^1.0.0",
        "dpd-clientlib": "^0.0.1",
        "dpd-dashboard": "^0.0.1",
        "express": "^4.16.2"
    },
    "scripts": {
        "start": "node server.js"
    },
```
host: heroku,
mongodb: mlab

**Comment by andreialecu** [comment]
@manoma2304 are you creating the collection from the dashboard while running it on heroku?

This is how heroku operates, see https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

You should set up your project locally, and publish your fully prepared project to heroku. Do not make any changes to collection structure or event scripts on heroku directly because you will lose them. The database itself won't be affected, since it's stored on a third party and is persistent.

**Comment by manoma2304** [comment]
i see, i came to this conclusion too, just not sure if it was the intended behavior, i didn't use heroku very much yet, thx for explaining
