### ISSUE TITLE
OnBeforeRequest & OnAfterCommit not working

### ISSUE THREAD

**Issue by PaulMaly** [deployd/deployd#876]
I'm trying to modify POST/PUT http response after it stored in DB using  OnAfterCommit but it's not working. (((

**Comment by andreialecu** [comment]
AfterCommit runs after POST/PUT have already sent out responses. You can change your app in such a way as to `emit()` something from AfterCommit instead, if that is feasible for you, and then handle the event via websocket in your client app.

**Comment by PaulMaly** [comment]
hm, this is not my case actually. I've an array of ids in resource and need to replace it with actual values from another resource for each type of request GET/POST/PUT. I did it in OnGet for GET requests and it works. But now I need to have the same thing for POST/PUT. Is it possible?

**Comment by andreialecu** [comment]
You should use [dpd-events](https://github.com/deployd/dpd-event) if you need to combine results from multiple resources. This allows you to make more efficient queries, by designing them in such a way that you get all the results at once instead of looping, and then using JavaScript to combine your resulting objects.

In my projects I usually always disable collection GET/POST/PUT (`if (!internal) cancel();`), then rely on various dpd-events to orchestrate actual functionality.

**Comment by PaulMaly** [comment]
Ok, thanks! I'll try!
